### ISSUE TITLE
Permission to use your screenshot code

### ISSUE THREAD

**Issue by rodjun** [ThisIsSoSteve/Project-Tensorflow-Cars#2]
Hey! I'm working on a simmilar project and after spending a lot of time trying to get a ctypes-only screenshot i gave up, just found out your project and i see you managed to do it, since there's no license I'm asking your permission to use it with credits to you. Thanks!

**Comment by ThisIsSoSteve** [comment]
Hey, i wish i could take credit but i got the code from here [https://gist.github.com/tzickel/5c2c51ddde7a8f5d87be730046612cd0](url)

Feel free to use any of the code. (really need to add license and readme files)
